### ISSUE TITLE
Readme needs set up instructions, and heroku link (?)

### ISSUE THREAD

**Issue by Jwhiles** [oliverjam/week5-zapo#40]
If there is anything unusual involved in setting up your project, making a config.env file for example, it's helpful to provide a step by step set up guide in the readme.

Also - did you get it hosted on Heroku? If so where? :)

**Comment by Jwhiles** [comment]
That said - the Guardian API seems to work without an API key, so maybe you should just remove env2.

**Comment by oliverjam** [comment]
Sorry, we didn't realise you'd be reviewing yet! The Guardian said we needed a key, but if it works without that's good too. The backend on Heroku has the key set-up so that version should work.

**Comment by Jwhiles** [comment]
The deadline was up! :)
