### ISSUE TITLE
Don't need to export each test

### ISSUE THREAD

**Issue by samhstn** [oliverjam/week5-zapo#42]
Instead of `require('./createDates.test.js')();` and `module.exporting` the wrapping function.

You could just `require('./createDates.test.js')();` and not export anything.

I find this pattern easier to read

**Comment by oliverjam** [comment]
Sorry @shouston3, we're slightly confused by this. Why would we not have to export the test to call it in another file?

**Comment by samhstn** [comment]
I'll be over in a sec

**Comment by ZooeyMiller** [comment]
closed by #61
