### ISSUE TITLE
Consider adding front end tests

### ISSUE THREAD

**Issue by joeylouise** [oliverjam/week5-zapo#45]

**Comment by pbywater** [comment]
We're only adding to the DOM in front end though 😢

**Comment by oliverjam** [comment]
Yeah we have three functions, two of which interact with the DOM and one which just makes an XHR. Not really sure there's much value in testing this/how we even would

**Comment by ZooeyMiller** [comment]
I'm closing this after chatting IRL with @joeylouise, our front end tests would be covered by integration tests but not unit tests.
