### ISSUE TITLE
Request can give you JSON if you ask for it

### ISSUE THREAD

**Issue by samhstn** [oliverjam/week5-zapo#46]
From [here](https://github.com/oliverjam/week5-zapo/blob/master/src/getObits.js#L14), you are just passing a string as the first argument and that's why it's not expecting JSON, if you instead pass an [options object](https://github.com/request/request#custom-http-headers) with the correct headers (`{url: url, json: true}`), then it will give you JSON back

**Comment by oliverjam** [comment]
Thank you! 👍 💯

**Comment by ZooeyMiller** [comment]
closed by #57
