### ISSUE TITLE
Heroku App Down - Router not catching a type of url extension

### ISSUE THREAD

**Issue by alexis-l8** [oliverjam/week5-zapo#48]
I typed the extension `/api?q=` and random numbers and unfortunately broke your app. You'll need to catch these weird numbers after this query.

**Comment by oliverjam** [comment]
Yup, this was for the still in-development feature where you can choose what date you want to view obituaries for. We removed the frontend data input but forgot to comment out the backend bit. This will be sanitised before it goes live!

**Comment by oliverjam** [comment]
This was fixed in #63
