### ISSUE TITLE
React, import, jsx eslint config?

### ISSUE THREAD

**Issue by samhstn** [oliverjam/week5-zapo#53]
Probably don't need these in your linting config or to have these as [dev dependencies](https://github.com/oliverjam/week5-zapo/blob/master/package.json#L27)

**Comment by oliverjam** [comment]
You're right, we used `eslint config` to set-up our linting automatically and the Airbnb Preset comes with React by default. We'll take it out.

**Comment by ZooeyMiller** [comment]
closed by #55
